# Generated by Django 2.0.4 on 2018-04-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem do produto')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
